# Generated by Django 4.1 on 2024-03-31 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientName", models.CharField(max_length=100)),
                ("patientEmail", models.CharField(max_length=100)),
                ("patientPhone", models.CharField(max_length=10)),
                ("appointmentDoctorName", models.CharField(max_length=100)),
                ("appointmentDate", models.CharField(max_length=50)),
                ("appointmentTime", models.CharField(max_length=50)),
                ("patientProblem", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("doctorName", models.CharField(max_length=100)),
                ("doctorDepartment", models.CharField(max_length=100)),
                ("doctorProfileImage", models.ImageField(upload_to="Doctors")),
                ("facebookLink", models.CharField(max_length=100)),
                ("twitterLink", models.CharField(max_length=100)),
                ("instagramLink", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Newsletter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Services",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("serviceName", models.CharField(max_length=100)),
                ("serviceDescription", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("patientName", models.CharField(max_length=100)),
                ("patientProfession", models.CharField(max_length=100)),
                ("patientImage", models.ImageField(upload_to="Patient Testimonial")),
                ("patientComments", models.TextField()),
            ],
        ),
    ]
