# Generated by Django 4.1 on 2024-03-31 14:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Services",
        ),
    ]
